[MIG] mail_composer_cc_bcc: Migration to 17.0
trisdoan/social pull request #3
Opened 2024-02-01 08:40 UTC by trisdoan

2024-02-01 13:46 UTC, nilshamerlinck requested changes
first quick pass

2024-02-01 13:46 UTC, nilshamerlinck commented on mail_composer_cc_bcc/models/mail_mail.py
bold move :) 

I understand that this big override might look a bit odd, but it was the only way we had found to get odoo to:
- send only one email (so that headers To: and Cc: are shown with all recipients, as end users expects)
- instead of sending one email per partner

I'm afraid it is still needed, unless proven otherwise?

Would need to copy-paste `_send()` from `mail_mail.py` in 17.0 and re-input the customized parts ("Same with native odoo" / "Different than native Odoo")

2024-02-01 13:46 UTC, nilshamerlinck commented on mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
we need this one to impact the Invoice sending wizard which is not a normal MailComposer wizard

2024-02-01 13:46 UTC, nilshamerlinck commented on mail_composer_cc_bcc/__manifest__.py
> +    "author": "Camptocamp SA, Odoo Community Association (OCA)",
```suggestion
    "author": "Camptocamp, Odoo Community Association (OCA)",
```

2024-02-01 13:46 UTC, nilshamerlinck commented on mail_composer_cc_bcc/__manifest__.py
> +    "author": "Camptocamp SA, Odoo Community Association (OCA)",
this was a request from Simone on migration of module to 16.0:

![image](https://github.com/trisdoan/social/assets/511258/923d84f2-857f-4570-9eed-1210d6a30f34)

somehow forgotten

2024-02-01 13:46 UTC, nilshamerlinck commented on mail_composer_cc_bcc/__manifest__.py
> +    "author": "Camptocamp SA, Odoo Community Association (OCA)",
`https://github.com/OCA/social/pull/1224#discussion_r1351694043`

2024-02-01 13:46 UTC, nilshamerlinck commented on mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
unless of course if you had planned to do this as part of same PR:

![image](https://github.com/trisdoan/social/assets/511258/ef73616f-0baf-44c6-bd37-c4233a6e3bc8)

which is a good idea!

2024-02-01 15:48 UTC, trisdoan commented on mail_composer_cc_bcc/models/mail_mail.py
Hi, you're right. I just tested with MailHog. What I did during development was checking mails in Odoo (settings -> technical -> mails). That's why I removed it initially as I thought it did not work in v17.

Will update as you suggested.

2024-02-01 15:53 UTC, trisdoan commented on mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
As I checked module account in v17, seems like Invoice sending wizard does not inherit from MailComposer which it did in v16.

So I agree a specific custom module for account is needed

2024-02-02 07:37 UTC, nilshamerlinck commented on mail_composer_cc_bcc/__manifest__.py
> +    "author": "Camptocamp SA, Odoo Community Association (OCA)",
can you put this small change in its own commit as requested by Simone?

2024-02-02 07:40 UTC, nilshamerlinck commented on mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
> -        self.assertIn(func_hash, VALID_HASHES)
can you keep this test? (and update hash)
this is a mechanism to let us know when upstream method got changed as we need to keep track of eventual important changes that we should update in our override as well

see `https://github.com/OCA/social/pull/1223` for example

2024-02-05 04:55 UTC, nilshamerlinck commented on mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
my bad, sorry I missed that somebody already did the job here: `https://github.com/OCA/social/pull/1283`
- can you run it in your local to make sure there is nothing blocking and then approve the PR? (Files changes > Review > Approve)
- then you can cherry-pick the commit in this PR + add a migration commit for `mail_composer_cc_bcc_account` as well

2024-02-06 02:27 UTC, trisdoan commented on mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
Morning anh @nilshamerlinck, about the 2nd point, it means

- I cherry-pick the commit to v16 to my forked repo

2024-02-06 02:43 UTC, trisdoan commented on mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
One more question, in `manifest.py`, author is: Camptocamp SA

- Should I request him to add authorship fix commit ?

2024-02-06 07:02 UTC, nilshamerlinck commented on mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
nah it's ok
later you'll create some backports PR to fix authorship in 16.0/15.0 and will take the occasion to do that

2024-02-19 07:35 UTC, closed without merging